import { PeriodicElement } from "./types";

// Full list of 118 elements
export const ELEMENTS: PeriodicElement[] = [
  // Period 1
  { number: 1, symbol: "H", name: "氫", atomic_mass: 1.008, category: "雙原子非金屬", xpos: 1, ypos: 1, summary: "宇宙中最豐富的元素。" },
  { number: 2, symbol: "He", name: "氦", atomic_mass: 4.0026, category: "稀有氣體", xpos: 18, ypos: 1, summary: "不會燃燒的氣體，讓氣球飄浮。" },

  // Period 2
  { number: 3, symbol: "Li", name: "鋰", atomic_mass: 6.94, category: "鹼金屬", xpos: 1, ypos: 2, summary: "最輕的金屬，用於電池。" },
  { number: 4, symbol: "Be", name: "鈹", atomic_mass: 9.0122, category: "鹼土金屬", xpos: 2, ypos: 2, summary: "用於X射線管的窗口。" },
  { number: 5, symbol: "B", name: "硼", atomic_mass: 10.81, category: "類金屬", xpos: 13, ypos: 2, summary: "植物細胞壁的重要成分。" },
  { number: 6, symbol: "C", name: "碳", atomic_mass: 12.011, category: "多原子非金屬", xpos: 14, ypos: 2, summary: "構成已知所有生命的基礎。" },
  { number: 7, symbol: "N", name: "氮", atomic_mass: 14.007, category: "雙原子非金屬", xpos: 15, ypos: 2, summary: "大氣中含量最多的氣體。" },
  { number: 8, symbol: "O", name: "氧", atomic_mass: 15.999, category: "雙原子非金屬", xpos: 16, ypos: 2, summary: "生物呼吸所需的元素。" },
  { number: 9, symbol: "F", name: "氟", atomic_mass: 18.998, category: "雙原子非金屬", xpos: 17, ypos: 2, summary: "反應性極強的氣體。" },
  { number: 10, symbol: "Ne", name: "氖", atomic_mass: 20.180, category: "稀有氣體", xpos: 18, ypos: 2, summary: "通電會發出紅光的氣體。" },

  // Period 3
  { number: 11, symbol: "Na", name: "鈉", atomic_mass: 22.990, category: "鹼金屬", xpos: 1, ypos: 3, summary: "食鹽的組成成分之一。" },
  { number: 12, symbol: "Mg", name: "鎂", atomic_mass: 24.305, category: "鹼土金屬", xpos: 2, ypos: 3, summary: "燃燒時發出耀眼白光。" },
  { number: 13, symbol: "Al", name: "鋁", atomic_mass: 26.982, category: "後過渡金屬", xpos: 13, ypos: 3, summary: "輕量且耐腐蝕的金屬。" },
  { number: 14, symbol: "Si", name: "矽", atomic_mass: 28.085, category: "類金屬", xpos: 14, ypos: 3, summary: "半導體產業的基礎。" },
  { number: 15, symbol: "P", name: "磷", atomic_mass: 30.974, category: "多原子非金屬", xpos: 15, ypos: 3, summary: "DNA和骨骼的重要成分。" },
  { number: 16, symbol: "S", name: "硫", atomic_mass: 32.06, category: "多原子非金屬", xpos: 16, ypos: 3, summary: "火山噴氣孔常見的黃色固體。" },
  { number: 17, symbol: "Cl", name: "氯", atomic_mass: 35.45, category: "雙原子非金屬", xpos: 17, ypos: 3, summary: "用於消毒和漂白。" },
  { number: 18, symbol: "Ar", name: "氬", atomic_mass: 39.948, category: "稀有氣體", xpos: 18, ypos: 3, summary: "填充在燈泡中防止氧化。" },

  // Period 4
  { number: 19, symbol: "K", name: "鉀", atomic_mass: 39.098, category: "鹼金屬", xpos: 1, ypos: 4, summary: "神經傳導必需的元素。" },
  { number: 20, symbol: "Ca", name: "鈣", atomic_mass: 40.078, category: "鹼土金屬", xpos: 2, ypos: 4, summary: "骨骼和牙齒的主要成分。" },
  { number: 21, symbol: "Sc", name: "鈧", atomic_mass: 44.956, category: "過渡金屬", xpos: 3, ypos: 4, summary: "用於強化鋁合金。" },
  { number: 22, symbol: "Ti", name: "鈦", atomic_mass: 47.867, category: "過渡金屬", xpos: 4, ypos: 4, summary: "強度高、重量輕，用於航太。" },
  { number: 23, symbol: "V", name: "釩", atomic_mass: 50.942, category: "過渡金屬", xpos: 5, ypos: 4, summary: "用於製造堅硬的鋼鐵工具。" },
  { number: 24, symbol: "Cr", name: "鉻", atomic_mass: 51.996, category: "過渡金屬", xpos: 6, ypos: 4, summary: "不鏽鋼中的防鏽成分。" },
  { number: 25, symbol: "Mn", name: "錳", atomic_mass: 54.938, category: "過渡金屬", xpos: 7, ypos: 4, summary: "用於製造乾電池。" },
  { number: 26, symbol: "Fe", name: "鐵", atomic_mass: 55.845, category: "過渡金屬", xpos: 8, ypos: 4, summary: "地球上使用最廣泛的金屬。" },
  { number: 27, symbol: "Co", name: "鈷", atomic_mass: 58.933, category: "過渡金屬", xpos: 9, ypos: 4, summary: "用於製造強力磁鐵。" },
  { number: 28, symbol: "Ni", name: "鎳", atomic_mass: 58.693, category: "過渡金屬", xpos: 10, ypos: 4, summary: "用於硬幣和電池。" },
  { number: 29, symbol: "Cu", name: "銅", atomic_mass: 63.546, category: "過渡金屬", xpos: 11, ypos: 4, summary: "優良的導電體。" },
  { number: 30, symbol: "Zn", name: "鋅", atomic_mass: 65.38, category: "過渡金屬", xpos: 12, ypos: 4, summary: "用於鍍在鐵上防鏽。" },
  { number: 31, symbol: "Ga", name: "鎵", atomic_mass: 69.723, category: "後過渡金屬", xpos: 13, ypos: 4, summary: "在手掌溫度下會融化的金屬。" },
  { number: 32, symbol: "Ge", name: "鍺", atomic_mass: 72.63, category: "類金屬", xpos: 14, ypos: 4, summary: "早期電晶體的材料。" },
  { number: 33, symbol: "As", name: "砷", atomic_mass: 74.922, category: "類金屬", xpos: 15, ypos: 4, summary: "著名的有毒物質。" },
  { number: 34, symbol: "Se", name: "硒", atomic_mass: 78.96, category: "多原子非金屬", xpos: 16, ypos: 4, summary: "用於影印機的感光鼓。" },
  { number: 35, symbol: "Br", name: "溴", atomic_mass: 79.904, category: "雙原子非金屬", xpos: 17, ypos: 4, summary: "常溫下為紅棕色液體。" },
  { number: 36, symbol: "Kr", name: "氪", atomic_mass: 83.798, category: "稀有氣體", xpos: 18, ypos: 4, summary: "用於高強度照明燈。" },

  // Period 5
  { number: 37, symbol: "Rb", name: "銣", atomic_mass: 85.468, category: "鹼金屬", xpos: 1, ypos: 5, summary: "用於原子鐘。" },
  { number: 38, symbol: "Sr", name: "鍶", atomic_mass: 87.62, category: "鹼土金屬", xpos: 2, ypos: 5, summary: "讓煙火呈現紅色。" },
  { number: 39, symbol: "Y", name: "釔", atomic_mass: 88.906, category: "過渡金屬", xpos: 3, ypos: 5, summary: "用於LED和螢光粉。" },
  { number: 40, symbol: "Zr", name: "鋯", atomic_mass: 91.224, category: "過渡金屬", xpos: 4, ypos: 5, summary: "用於核反應爐的燃料棒護套。" },
  { number: 41, symbol: "Nb", name: "鈮", atomic_mass: 92.906, category: "過渡金屬", xpos: 5, ypos: 5, summary: "用於超導磁鐵。" },
  { number: 42, symbol: "Mo", name: "鉬", atomic_mass: 95.95, category: "過渡金屬", xpos: 6, ypos: 5, summary: "植物固氮酶的關鍵成分。" },
  { number: 43, symbol: "Tc", name: "鎝", atomic_mass: 98, category: "過渡金屬", xpos: 7, ypos: 5, summary: "第一個人工合成的元素。" },
  { number: 44, symbol: "Ru", name: "釕", atomic_mass: 101.07, category: "過渡金屬", xpos: 8, ypos: 5, summary: "用於電子接觸點。" },
  { number: 45, symbol: "Rh", name: "銠", atomic_mass: 102.91, category: "過渡金屬", xpos: 9, ypos: 5, summary: "最昂貴的貴金屬之一。" },
  { number: 46, symbol: "Pd", name: "鈀", atomic_mass: 106.42, category: "過渡金屬", xpos: 10, ypos: 5, summary: "用於汽車廢氣轉化器。" },
  { number: 47, symbol: "Ag", name: "銀", atomic_mass: 107.87, category: "過渡金屬", xpos: 11, ypos: 5, summary: "導電性最好的金屬。" },
  { number: 48, symbol: "Cd", name: "鎘", atomic_mass: 112.41, category: "過渡金屬", xpos: 12, ypos: 5, summary: "有毒，曾用於顏料。" },
  { number: 49, symbol: "In", name: "銦", atomic_mass: 114.82, category: "後過渡金屬", xpos: 13, ypos: 5, summary: "觸控螢幕的關鍵材料。" },
  { number: 50, symbol: "Sn", name: "錫", atomic_mass: 118.71, category: "後過渡金屬", xpos: 14, ypos: 5, summary: "用於焊接。" },
  { number: 51, symbol: "Sb", name: "銻", atomic_mass: 121.76, category: "類金屬", xpos: 15, ypos: 5, summary: "用於阻燃劑。" },
  { number: 52, symbol: "Te", name: "碲", atomic_mass: 127.60, category: "類金屬", xpos: 16, ypos: 5, summary: "用於太陽能板。" },
  { number: 53, symbol: "I", name: "碘", atomic_mass: 126.90, category: "雙原子非金屬", xpos: 17, ypos: 5, summary: "甲狀腺素的成分。" },
  { number: 54, symbol: "Xe", name: "氙", atomic_mass: 131.29, category: "稀有氣體", xpos: 18, ypos: 5, summary: "用於閃光燈和離子推進器。" },

  // Period 6
  { number: 55, symbol: "Cs", name: "銫", atomic_mass: 132.91, category: "鹼金屬", xpos: 1, ypos: 6, summary: "定義「秒」的標準。" },
  { number: 56, symbol: "Ba", name: "鋇", atomic_mass: 137.33, category: "鹼土金屬", xpos: 2, ypos: 6, summary: "用於消化道X光檢查。" },
  // Lanthanides are 57-71, placed below
  { number: 72, symbol: "Hf", name: "鉿", atomic_mass: 178.49, category: "過渡金屬", xpos: 4, ypos: 6, summary: "用於核潛艇的控制棒。" },
  { number: 73, symbol: "Ta", name: "鉭", atomic_mass: 180.95, category: "過渡金屬", xpos: 5, ypos: 6, summary: "用於手機電容器。" },
  { number: 74, symbol: "W", name: "鎢", atomic_mass: 183.84, category: "過渡金屬", xpos: 6, ypos: 6, summary: "熔點最高的金屬。" },
  { number: 75, symbol: "Re", name: "錸", atomic_mass: 186.21, category: "過渡金屬", xpos: 7, ypos: 6, summary: "用於噴射引擎葉片。" },
  { number: 76, symbol: "Os", name: "鋨", atomic_mass: 190.23, category: "過渡金屬", xpos: 8, ypos: 6, summary: "密度最高的元素之一。" },
  { number: 77, symbol: "Ir", name: "銥", atomic_mass: 192.22, category: "過渡金屬", xpos: 9, ypos: 6, summary: "非常抗腐蝕，隕石中常見。" },
  { number: 78, symbol: "Pt", name: "鉑", atomic_mass: 195.08, category: "過渡金屬", xpos: 10, ypos: 6, summary: "俗稱白金，用於催化劑。" },
  { number: 79, symbol: "Au", name: "金", atomic_mass: 196.97, category: "過渡金屬", xpos: 11, ypos: 6, summary: "延展性極佳的貴金屬。" },
  { number: 80, symbol: "Hg", name: "汞", atomic_mass: 200.59, category: "過渡金屬", xpos: 12, ypos: 6, summary: "常溫下唯一的液態金屬。" },
  { number: 81, symbol: "Tl", name: "鉈", atomic_mass: 204.38, category: "後過渡金屬", xpos: 13, ypos: 6, summary: "劇毒重金屬。" },
  { number: 82, symbol: "Pb", name: "鉛", atomic_mass: 207.2, category: "後過渡金屬", xpos: 14, ypos: 6, summary: "用於阻擋輻射。" },
  { number: 83, symbol: "Bi", name: "鉍", atomic_mass: 208.98, category: "後過渡金屬", xpos: 15, ypos: 6, summary: "結晶呈現美麗的彩虹色。" },
  { number: 84, symbol: "Po", name: "釙", atomic_mass: 209, category: "類金屬", xpos: 16, ypos: 6, summary: "居里夫人發現的放射性元素。" },
  { number: 85, symbol: "At", name: "砈", atomic_mass: 210, category: "類金屬", xpos: 17, ypos: 6, summary: "極稀有的放射性元素。" },
  { number: 86, symbol: "Rn", name: "氡", atomic_mass: 222, category: "稀有氣體", xpos: 18, ypos: 6, summary: "無色無味的放射性氣體。" },

  // Period 7
  { number: 87, symbol: "Fr", name: "鍅", atomic_mass: 223, category: "鹼金屬", xpos: 1, ypos: 7, summary: "極不穩定，會迅速衰變。" },
  { number: 88, symbol: "Ra", name: "鐳", atomic_mass: 226, category: "鹼土金屬", xpos: 2, ypos: 7, summary: "曾經用於發光手錶指針。" },
  // Actinides are 89-103, placed below
  { number: 104, symbol: "Rf", name: "鑪", atomic_mass: 267, category: "過渡金屬", xpos: 4, ypos: 7, summary: "以拉塞福命名。" },
  { number: 105, symbol: "Db", name: "𨧀", atomic_mass: 268, category: "過渡金屬", xpos: 5, ypos: 7, summary: "人工合成元素。" },
  { number: 106, symbol: "Sg", name: "𨭎", atomic_mass: 269, category: "過渡金屬", xpos: 6, ypos: 7, summary: "以西博格命名。" },
  { number: 107, symbol: "Bh", name: "𨨏", atomic_mass: 270, category: "過渡金屬", xpos: 7, ypos: 7, summary: "以波耳命名。" },
  { number: 108, symbol: "Hs", name: "𨭆", atomic_mass: 277, category: "過渡金屬", xpos: 8, ypos: 7, summary: "性質類似鋨。" },
  { number: 109, symbol: "Mt", name: "䥑", atomic_mass: 278, category: "過渡金屬", xpos: 9, ypos: 7, summary: "為了紀念邁特納。" },
  { number: 110, symbol: "Ds", name: "鐽", atomic_mass: 281, category: "過渡金屬", xpos: 10, ypos: 7, summary: "以德國城市達姆施塔特命名。" },
  { number: 111, symbol: "Rg", name: "錀", atomic_mass: 282, category: "過渡金屬", xpos: 11, ypos: 7, summary: "以倫琴命名。" },
  { number: 112, symbol: "Cn", name: "鎶", atomic_mass: 285, category: "過渡金屬", xpos: 12, ypos: 7, summary: "以哥白尼命名。" },
  { number: 113, symbol: "Nh", name: "鉨", atomic_mass: 286, category: "後過渡金屬", xpos: 13, ypos: 7, summary: "第一個由亞洲國家發現的元素。" },
  { number: 114, symbol: "Fl", name: "鈇", atomic_mass: 289, category: "後過渡金屬", xpos: 14, ypos: 7, summary: "以弗廖羅夫實驗室命名。" },
  { number: 115, symbol: "Mc", name: "鏌", atomic_mass: 290, category: "後過渡金屬", xpos: 15, ypos: 7, summary: "以莫斯科命名。" },
  { number: 116, symbol: "Lv", name: "鉝", atomic_mass: 293, category: "後過渡金屬", xpos: 16, ypos: 7, summary: "以利弗莫爾實驗室命名。" },
  { number: 117, symbol: "Ts", name: "鿬", atomic_mass: 294, category: "類金屬", xpos: 17, ypos: 7, summary: "以田納西州命名。" },
  { number: 118, symbol: "Og", name: "鿫", atomic_mass: 294, category: "稀有氣體", xpos: 18, ypos: 7, summary: "目前原子序最大的元素。" },

  // Lanthanides (Row 9, placed from col 3 to 17)
  { number: 57, symbol: "La", name: "鑭", atomic_mass: 138.91, category: "鑭系元素", xpos: 3, ypos: 9, summary: "混合稀土金屬的主要成分。" },
  { number: 58, symbol: "Ce", name: "鈰", atomic_mass: 140.12, category: "鑭系元素", xpos: 4, ypos: 9, summary: "用於打火石。" },
  { number: 59, symbol: "Pr", name: "鐠", atomic_mass: 140.91, category: "鑭系元素", xpos: 5, ypos: 9, summary: "用於焊接護目鏡。" },
  { number: 60, symbol: "Nd", name: "釹", atomic_mass: 144.24, category: "鑭系元素", xpos: 6, ypos: 9, summary: "製造最強力的永久磁鐵。" },
  { number: 61, symbol: "Pm", name: "鉕", atomic_mass: 145, category: "鑭系元素", xpos: 7, ypos: 9, summary: "唯一放射性的鑭系元素。" },
  { number: 62, symbol: "Sm", name: "釤", atomic_mass: 150.36, category: "鑭系元素", xpos: 8, ypos: 9, summary: "用於高溫磁鐵。" },
  { number: 63, symbol: "Eu", name: "銪", atomic_mass: 151.96, category: "鑭系元素", xpos: 9, ypos: 9, summary: "用於歐元防偽螢光。" },
  { number: 64, symbol: "Gd", name: "釓", atomic_mass: 157.25, category: "鑭系元素", xpos: 10, ypos: 9, summary: "用於MRI顯影劑。" },
  { number: 65, symbol: "Tb", name: "鋱", atomic_mass: 158.93, category: "鑭系元素", xpos: 11, ypos: 9, summary: "用於綠色螢光粉。" },
  { number: 66, symbol: "Dy", name: "鏑", atomic_mass: 162.50, category: "鑭系元素", xpos: 12, ypos: 9, summary: "用於硬碟驅動器。" },
  { number: 67, symbol: "Ho", name: "鈥", atomic_mass: 164.93, category: "鑭系元素", xpos: 13, ypos: 9, summary: "用於雷射手術。" },
  { number: 68, symbol: "Er", name: "鉺", atomic_mass: 167.26, category: "鑭系元素", xpos: 14, ypos: 9, summary: "用於光纖放大器。" },
  { number: 69, symbol: "Tm", name: "銩", atomic_mass: 168.93, category: "鑭系元素", xpos: 15, ypos: 9, summary: "最稀有的稀土元素之一。" },
  { number: 70, symbol: "Yb", name: "鐿", atomic_mass: 173.05, category: "鑭系元素", xpos: 16, ypos: 9, summary: "用於不鏽鋼合金。" },
  { number: 71, symbol: "Lu", name: "鎦", atomic_mass: 174.97, category: "鑭系元素", xpos: 17, ypos: 9, summary: "用於癌症治療。" },

  // Actinides (Row 10, placed from col 3 to 17)
  { number: 89, symbol: "Ac", name: "錒", atomic_mass: 227, category: "錒系元素", xpos: 3, ypos: 10, summary: "強放射性，發出藍光。" },
  { number: 90, symbol: "Th", name: "釷", atomic_mass: 232.04, category: "錒系元素", xpos: 4, ypos: 10, summary: "潛在的核能燃料。" },
  { number: 91, symbol: "Pa", name: "鏷", atomic_mass: 231.04, category: "錒系元素", xpos: 5, ypos: 10, summary: "非常稀有且昂貴。" },
  { number: 92, symbol: "U", name: "鈾", atomic_mass: 238.03, category: "錒系元素", xpos: 6, ypos: 10, summary: "核電廠的主要燃料。" },
  { number: 93, symbol: "Np", name: "錼", atomic_mass: 237, category: "錒系元素", xpos: 7, ypos: 10, summary: "首個超鈾元素。" },
  { number: 94, symbol: "Pu", name: "鈽", atomic_mass: 244, category: "錒系元素", xpos: 8, ypos: 10, summary: "用於核武器和太空探測器。" },
  { number: 95, symbol: "Am", name: "鋂", atomic_mass: 243, category: "錒系元素", xpos: 9, ypos: 10, summary: "用於煙霧偵測器。" },
  { number: 96, symbol: "Cm", name: "鋦", atomic_mass: 247, category: "錒系元素", xpos: 10, ypos: 10, summary: "以居里夫婦命名。" },
  { number: 97, symbol: "Bk", name: "鉳", atomic_mass: 247, category: "錒系元素", xpos: 11, ypos: 10, summary: "以柏克萊命名。" },
  { number: 98, symbol: "Cf", name: "鉲", atomic_mass: 251, category: "錒系元素", xpos: 12, ypos: 10, summary: "極強的中子源。" },
  { number: 99, symbol: "Es", name: "鑀", atomic_mass: 252, category: "錒系元素", xpos: 13, ypos: 10, summary: "以愛因斯坦命名。" },
  { number: 100, symbol: "Fm", name: "鐨", atomic_mass: 257, category: "錒系元素", xpos: 14, ypos: 10, summary: "以費米命名。" },
  { number: 101, symbol: "Md", name: "鍆", atomic_mass: 258, category: "錒系元素", xpos: 15, ypos: 10, summary: "以門得列夫命名。" },
  { number: 102, symbol: "No", name: "鍩", atomic_mass: 259, category: "錒系元素", xpos: 16, ypos: 10, summary: "以諾貝爾命名。" },
  { number: 103, symbol: "Lr", name: "鐒", atomic_mass: 266, category: "錒系元素", xpos: 17, ypos: 10, summary: "以勞倫斯命名。" },
];

export const CATEGORY_COLORS: Record<string, string> = {
  "雙原子非金屬": "bg-blue-200 border-blue-400 text-blue-900",
  "稀有氣體": "bg-purple-200 border-purple-400 text-purple-900",
  "鹼金屬": "bg-red-200 border-red-400 text-red-900",
  "鹼土金屬": "bg-orange-200 border-orange-400 text-orange-900",
  "類金屬": "bg-teal-200 border-teal-400 text-teal-900",
  "多原子非金屬": "bg-green-200 border-green-400 text-green-900",
  "後過渡金屬": "bg-gray-300 border-gray-500 text-gray-900",
  "過渡金屬": "bg-yellow-200 border-yellow-400 text-yellow-900",
  "鑭系元素": "bg-pink-200 border-pink-400 text-pink-900",
  "錒系元素": "bg-rose-300 border-rose-500 text-rose-900",
};

// Fun animal villager personas for Gemini system instructions (Translated to Chinese)
export const VILLAGER_PERSONAS = [
  "你是一個悠閒、愛吃零食的村民（喜歡蟲子）。你把所有事情都跟食物或睡午覺聯想在一起。口頭禪是「吸溜」。",
  "你是一個充滿活力的偶像型村民。你使用很多「！」並想出名。口頭禪是「閃亮」。",
  "你是一個聲音低沉的暴躁型長輩村民。你脾氣不好但很有智慧。口頭禪是「哼」。",
  "你是一個運動型村民。你把化學跟健身和肌肉聯想在一起。口頭禪是「加油」。",
  "你是一個普通、溫柔的村民，喜歡閱讀和自然。口頭禪是「呢」。",
];